export default [
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_008.jpeg",
        title: "厨房厨柜定制整体套装",
        tag: "近期浏览过万",
        price: "2800.00",
        evaluate: 2000,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_006.jpeg",
        title: "被套床单三件套",
        tag: "100%好评",
        price: "48.00",
        evaluate: 800,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_010.jpeg",
        title: "【特价捡漏】高档轻奢品牌设计感小众衬衣女2022夏季新款清凉休闲女式百搭短袖棉质格纹衬衫",
        tag: "近期浏览过万",
        price: "29.90",
        evaluate: 12000,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_011.jpeg",
        title: "丝袜女夏季超薄性感黑丝显瘦美腿袜纯欲风长筒打底连裤袜",
        tag: "100%好评",
        price: "8.90",
        evaluate: 1100,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_006.jpeg",
        title: "学生宿舍被套床单三件套寝室床上被褥套装被子全套 150×200cm",
        tag: "100%好评",
        price: "48.00",
        evaluate: 800,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_008.jpeg",
        title: "厨房厨柜定制整体套装石英石台面装修家用一体灶台柜吊柜碗橱柜",
        tag: "近期浏览过万",
        price: "2800.00",
        evaluate: 2000,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_011.jpeg",
        title: "丝袜女夏季超薄性感黑丝显瘦美腿袜纯欲风长筒打底连裤袜",
        tag: "100%好评",
        price: "8.90",
        evaluate: 1100,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_006.jpeg",
        title: "学生宿舍被套床单三件套寝室床上被褥套装被子全套 150×200cm",
        tag: "100%好评",
        price: "48.00",
        evaluate: 800,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_008.jpeg",
        title: "厨房厨柜定制整体套装",
        tag: "近期浏览过万",
        price: "2800.00",
        evaluate: 2000,
    },
    {
        src: "https://res.firstui.cn/static/images/component/waterfall/P_006.jpeg",
        title: "被套床单三件套",
        tag: "100%好评",
        price: "48.00",
        evaluate: 800,
    },
];
