export default [
    {
        cn: "列表",
        en: "LIST",
        src: "list",
        background: "#F8F4FF",
        page: "/pages/component/layout/list/list",
    },
    {
        cn: "索引列表",
        en: "INDEX LIST",
        src: "index_list",
        background: "#EDF9FF",
        page: "/pages/component/nav/indexList/indexList",
    },
    {
        cn: "宫格",
        en: "GRID",
        src: "grid",
        background: "#EAFFF6",
        page: "/pages/component/layout/grid/grid",
    },
    {
        cn: "卡片",
        en: "CARD",
        src: "card",
        background: "#FFF4F7",
        page: "/pages/component/layout/card/card",
    },
    {
        cn: "瀑布流",
        en: "WATERFALL FLOW",
        src: "waterfall_flow",
        background: "#FFF8EF",
        page: "/pages/layout/waterfall/waterfall",
    },
    {
        cn: "顶部选项卡",
        en: "TOP TAB",
        src: "tabs",
        background: "#F8F4FF",
        page: "/pages/layout/topTab/topTab",
    },
    {
        cn: "垂直选项卡",
        en: "VERTICAL TAB",
        src: "vertical",
        background: "#EDF9FF",
        page: "/pages/component/nav/vtabs/vtabs",
    },
    {
        cn: "新闻列表",
        en: "NEWS LIST",
        src: "news",
        background: "#EAFFF6",
        page: "/pages/layout/newsList/newsList",
    },
    {
        cn: "商品列表",
        en: "PRODUCT LIST",
        src: "goodslist",
        background: "#FFF4F7",
        page: "/pages/layout/productList/productList",
    },
    {
        cn: "提交订单栏",
        en: "SUBMIT BAR",
        src: "submit",
        background: "#FFF8EF",
        page: "/pages/layout/submitBar/submitBar",
    },
    {
        cn: "商品导航栏",
        en: "GOODS BAR",
        src: "commodity",
        background: "#F8F4FF",
        page: "/pages/layout/goodsBar/goodsBar",
    },
    {
        cn: "聊天栏",
        en: "CHAT BAR",
        src: "chat",
        background: "#EDF9FF",
        page: "/pages/layout/chatBar/chatBar",
    },
    {
        cn: "滚动消息",
        en: "ROLL NEWS",
        src: "roll",
        background: "#EAFFF6",
        page: "/pages/layout/rollNews/rollNews",
    },
    {
        cn: "卡片轮播",
        en: "CARD SWIPER",
        src: "rotation",
        background: "#FFF4F7",
        page: "/pages/layout/cardSwiper/cardSwiper",
    },
    {
        cn: "地图",
        en: "MAP",
        src: "map",
        background: "#FFF8EF",
        page: "/pages/layout/map/map",
    },
    {
        cn: "横向滚动",
        en: "ROLL HORIZONTAL",
        src: "transverse",
        background: "#F8F4FF",
        page: "/pages/layout/rollHor/rollHor",
    },
];
